name: Supervisor Coding Standards

on:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP 7.4 and disable opcache
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: :opcache

      - name: Composer
        run: composer install

      - name: Check coding standards
        run: composer run phpcs $(git diff --name-only master..${{ github.head_ref }} -- '*.php')
